
//server.port:8080
spring:
datasource:
url: jdbc:postgresql://localhost:5432/lojaVirtual2?useTimezone=true&serverTimezone=UTC&useLegacyDate
username: postgre
password: root
jpa:
show-sql: true
hibernate:
ddl-auto: update
properties:
hibernate.format_sql: true

logging:
level:
org:
hibernate:
type: trace

//https://jdbc.postgresql.org
